# Generated by Django 4.1.5 on 2023-04-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_adobe_apple_cisco_ey_facebook_google_infosys_netflix_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="mahindra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
    ]
