# Generated by Django 4.2.5 on 2024-02-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_mahindra"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=122)),
                ("lastname", models.CharField(max_length=122)),
                ("phonenumber", models.CharField(max_length=20)),
            ],
        ),
    ]
